package jw.core;
import java.util.*;

import static jw.core.MudMain.*;

/**
	The Lootgroup class represents a single loot group, which contains a selection
	of items to be generated by mobs on death.
*/
public class Lootgroup
{
	/** The lootgroup's ID number. */
	public int id;
	/** The name of this lootgroup. */
	public String name = "";
	/** The list of items contained in this lootgroup. */
	public HashMap<ObjProto, Integer> contents = new HashMap<ObjProto, Integer>();
	
	public Lootgroup(int newId)
	{
		id = newId;
	}
	
	public static Lootgroup lookup(int targetId)
	{
		for (Lootgroup l : lootgroups)
			if (l.id == targetId)
				return l;
		return null;
	}
	
	public ObjData getObject()
	{
		ObjProto tempOp = null;

		int totalNum = 0;
		for (ObjProto k : contents.keySet())
			totalNum += contents.get(k);
		
		int targetNum = gen.nextInt(totalNum);
		for (ObjProto k : contents.keySet())
		{
			targetNum -= contents.get(k);
			if (targetNum < 0)
			{
				tempOp = k;
				break;
			}
		}

		if (tempOp == null)
		{
			sysLog("bugs", "Lootgroup #"+id+" produced an invalid object ID.");
			return new ObjData(objProtos.get(0));
		}
		return new ObjData(tempOp);
	}
}